## parameters used across different nodes
crs_metric: "EPSG:2157"
crs_latlon: "EPSG:4326"
pollutant: "NO2_ugm3"
timestamp_column: "gps_timestamp"
latitude_column: "latitude"
longitude_column: "longitude"

## the following params are used to aggregate data point
## at different spatial units; one may select the preferred unit(s)
## among the ones below
spatial_unit_1_ED: "ED"
ED_min_obs_count: null
spatial_unit_2_hex: "hex"
hex_min_obs_count: 0.1
spatial_unit_3_road: "road"
road_buffer_context: 100 # meter
road_min_obs_count: 0.1


## parameters to process the street network
## used in function: OSM_roads
## node name: osm_roads_node
place_name: "Dublin, Ireland"
directions:
  - "upper"
  - "lower"
abbreviations:
  st: "street"
  rd: "road"
  ave: "avenue"
  blvd: "boulevard"
words_to_rm:
  - "street"
  - "st"
  - "road"
  - "rd"
  - "square"
  - "ave"
  - "avenue"
  - "drive"


## parameters used to read and filter raw air quality data
## you should modify the below accoding to your own air quality data
## function: get_air
## node name: filtered_raw_air
start_time: "2021-11-01T00:00:00"
end_time: "2022-03-31T23:59:59"


## parameters for Valhalla Docker map-matching
## NOTE: DO **NOT** change the Valhalla Docker parameters unless you specifically set your docker image with different settings
## function/node: run_valhalla_mapmatching
## node name: map_match
use_valhalla: True
valhalla_docker_img: "gisops_docker_valhalla_1"
MAX_POINTS: 16000
MIN_POINTS: 10
MINUTES_TIME_GAP: 5


## ----------------------------------------------------------
##   All the below parameters refers to covariates data
## ----------------------------------------------------------

# optional params:
# they refer to the period of data collection of
# AIR data, and they are used to match the temporal dimension
# of the covariates (filtering):
weekdays_only: True # whether air data were collected only on weekdays (bool)
traffic_data_type: "raw" # Dublin SCATS data are raw hourly data to be aggregated
start_hour: 9 # hour of beginning of data collection (included)
end_hour: 17 # hour of end of data collection (excluded)


## TRAFFIC DATA: 
## used in traffic_pipeline
# needed column names and format
traffic_timestamp_col: "End_Time"
traffic_timestamp_format: "%Y%m%d%H%M%S" 
traffic_count_col: "Sum_Volume"
traffic_sites_ID: "Site"

# site ID column of file containing traffic site GEOMETRIES
# (if geometries are in a separate file, else use traffic_sites_ID again):
traffic_ID_locationfile: "SiteID" 


## -------------------------------
##     GWR / MGWR modelling
## -------------------------------
gwr_kernel: "exponential"
mgwr_kernel: "exponential"

# random search
exhaustive_search: "all"
n_random_search: 100
test_model_1: "GWR"
test_model_2: "MGWR"