## parameters used across different nodes
crs_metric: "EPSG:2157"
crs_latlon: "EPSG:4326"
pollutant: "NO2_ugm3"
timestamp_column: "gps_timestamp"
latitude_column: "latitude"
longitude_column: "longitude"

## the following params are used to aggregate data point
## at different spatial units; one may select the preferred unit(s)
## among the ones below
spatial_unit_1_ED: "ED"
spatial_unit_2_hex: "hex"
spatial_unit_3_road: "road"


## parameters to process the street network
## used in function: OSM_roads
## node name: osm_roads_node
place_name: "Dublin, Ireland"
directions:
  - "upper"
  - "lower"
abbreviations:
  st: "street"
  rd: "road"
  ave: "avenue"
  blvd: "boulevard"
words_to_rm:
  - "street"
  - "st"
  - "road"
  - "rd"
  - "square"
  - "ave"
  - "avenue"
  - "drive"


## parameters used to read and filter raw air quality data
## you should modify the below accoding to your own air quality data
## function: get_air
## node name: filtered_raw_air
start_time: "2021-11-01T00:00:00"
end_time: "2022-03-31T23:59:59"


## parameters for Valhalla Docker map-matching
## NOTE: DO **NOT** change the Valhalla Docker parameters unless you specifically set your docker image with different settings
## function/node: run_valhalla_mapmatching
## node name: map_match
use_valhalla: True
valhalla_docker_img: "gisops_docker_valhalla_1"
MAX_POINTS: 16000
MIN_POINTS: 10
MINUTES_TIME_GAP: 5
